import React from 'react';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import Welcome from '../components/Welcome';

import styled from 'styled-components';

import { auth, db } from '../firebase';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useCollection } from 'react-firebase-hooks/firestore';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Chatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Welcome />
    </Container>
  );
}

export async function getServerSideProps() {
  const ref = await db.collection('chats').get();

  const chats = ref.docs
    .map(doc => (doc.data()))
    .map(chats => ({
      userLoggedIn: chats.users[0],
      recipientEmail: chats.users[1]
    }));

  return {
    props: {
      usersInChat: chats
    }
  };
}

const Container = styled.div`
  background-color: #2e2e2e;
  display: flex;
`;
