import React from 'react';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import Welcome from '../components/Welcome';

import { db } from '../firebase';

export default function Home() {
  return (
    <div style={{ backgroundColor: '#2e2e2e', display: 'flex' }}>
      <Head>
        <title>Chatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Welcome />
    </div>
  );
}

export async function getServerSideProps() {
  const ref = await db.collection('chats').get();

  const chats = ref.docs
    .map(doc => (doc.data()))
    .map(chats => ({
      userLoggedIn: chats.users[0],
      recipientEmail: chats.users[1]
    }));

  return {
    props: {}
  };
}
